Cargo.toml
src/bin/addr2line.rs
src/error.rs
src/lib.rs

Sorry for not breaking this down into smaller commits, but there wasn't a good way of doing that without the intermittent commits being unintuitive, broken, or both. This moves all the logic into the library, provides a documented API (with `#[deny(missing_docs)]`), and extends the binary such that its interface matches that of `addr2line`. It builds cleanly on both stable and nightly.
Next steps would probably be to add support for extracting containing function, not just file + line. I *think* this shouldn't be too painful, but you never know. I would also like to try and find a good way to test this, but I'm not entirely sure how to go about that. Suggestions welcome!
The darkest corners of this PR is the nested use of `owning_ref::OwningHandle`. This is necessary so that we can …

Clean up addr2line so it is a real library

---

.travis.yml

The current `.travis.yml` file contains a number of unnecessary elements that this PR removes. This decreases overall build time, as well as getting rid of unneeded complexity.
In particular:
- `sudo: false` is the default for all new Travis builds,
- `osx_image: xcode7.1` is no longer valid -- the default is `xcode7.3`, and all lower versions are automatically bumped.
- `brew update` and `brew install python` on osx: not needed, as `python2.7` is always installed on Travis

Use a simpler but equivalent `.travis.yml` file

---

.travis.yml
Cargo.toml
build.rs
tests/integration_test.rs

While not particularly extensive, this PR adds the first `addr2line` integration test. It compares the output of the system `addr2line` program with that of the library, and makes sure that whenever we give affirmative answers, our answers match that of the original `addr2line`. It also demonstrates how to write integration tests in a reasonably straightforward manner that also work on Travis, and actually exercises a surprising fraction of the code
Note that the tests [currently fail on macOS](https://travis-ci.org/jonhoo/addr2line/builds/181077541), apparently because the `debug_info` section is missing from the compiled binary. Neither forcing `clang` nor `-gdwarf-4` made a difference. Given that I don't have a macOS computer to test on, I'd appreciate it if someone who does could try …

Add integration tests

---

.travis.yml
Cargo.toml
src/bin/addr2line.rs
src/lib.rs
tests/integration_test.rs

This PR adds support for returning information about the function that contains a given address, in addition to the file and line numbers. Since supporting this means we have to store and search more DIEs, the user may choose whether or not they want function information by constructing a `Mapping` with either `with_functions` or just `new`. Current benchmarks suggest that we still do okay in terms of performance:
```console
$ addr2line
real	0m1.392s
user	0m1.370s
sys	0m0.017s
$ target/release/addr2line
real	0m1.592s
user	0m1.587s
sys	0m0.000s
$ addr2line -f
real	0m1.365s
user	0m1.340s
sys	0m0.023s
$ target/release/addr2line -f
real	0m1.661s
user	0m1.643s
sys	0m0.010s
```
It is unclear if we can keep using a `Vec` for the `units` with this setup, as it may become quite expensive to search …

Add support for finding functions for addresses

---

Cargo.toml
src/bin/addr2line.rs

This PR adds support for symbol demangling in the `addr2line` binary when run with the `-C` flag (similar to GNU binutils `addr2line`). It uses @alexcrichton's [rustc-demangle](https://github.com/alexcrichton/rustc-demangle) crate, which provides demangling for Rust's standard mangling, but which probably catches various mangles performed by other compilers too.
Will rebase once #8 and #9 have been merged.

Add support for symbol demangling in addr2line binary

---

tests/integration_test.rs

Previously, the test cases checked first the file, and then the line number. This meant that if the line number diverged, the file in question was not printed. This PR changes this behavior such that file and line number are checked in a single `assert_eq!`.
#15 should be merged prior to this, and then this should be rebased.

Minor: Test file and line equality simultaneously

---

.gitignore
bench.plot.r
benchmark.sh

Following @fitzgen's request in #18, here are the scripts I used to generate the plots in #14 and #19. I cleaned them up a fair bit, though they could probably still use some more cleaning. You will need `R` installed, along with the `ggplot2` package.
Invoke as
```console
$ ./benchmark.sh path/to/executable master somebranch 7fdd85ef
```
or if you already have a bunch of addresses in `addresses.txt`:
```console
$ ./benchmark.sh path/to/executable addresses.txt master somebranch 7fdd85ef
```
Results are in `./time.png` and `./memory.png`.

Add benchmarking script

---

.gitignore
bench.plot.r
benchmark.sh

Following suggestions [on Reddit](https://www.reddit.com/r/rust/comments/5i4yms/the_rust_and_gimli_port_of_addr2line_is_now_an/db5dpt9/), this PR adds `eu-addr2line` from elfutils and `llvm-symbolizer` from llvm to the baseline comparisons in our benchmark. It also cleans up the plotting scripts a little more and enhances the resulting graphs.
Current benchmarking results (i.e., not with #19):

Add benchmark comparison against other addr2line implementations

---

benchmark.sh

This stashes all changes before running the benchmark, and then pops those changes again (if there were any) after all the binaries have been built. Note that we also need to do a some trickery here to make sure that the bash script doesn't do weird things because we modified it while it was executing (which would happen if `benchmark.sh` itself was dirty).
This patch is best viewed with [`git diff -w`](https://github.com/gimli-rs/addr2line/pull/23/commits/708c18a0fd921bd1e9b3588ac8b322917de1ab3f?w=1)

Allow running benchmark.sh while repo is dirty

---

Cargo.toml

Now that gimli [0.11.0](https://github.com/gimli-rs/gimli/commit/2a8d3286cb7f3cdede333813d74fbe6e30aa8aaf) and owning-ref [2.2.4](https://github.com/Kimundi/owning-ref-rs/commit/c00676ea361eae657cfda05bf14fbca3390d0a23) are both out, all the features we depend on from those crates have been released. This PR replaces the git dependencies for those crates with the appropriate version dependencies instead, which should also allow us to publish a new (and much needed) version of addr2line to crates.io.

Remove all git dependencies

---

Cargo.toml

Not terribly important, but since we've been doing a pass on `Cargo.toml` anyway..

Add Phillip and Jon as authors

---

.travis.yml
Cargo.toml
src/bin/addr2line.rs
src/lib.rs
tests/integration_test.rs

The `cpp_demangle` crate doesn't match libiberty 100% yet, but it is in a good enough place that we can get some utility out of it here.
Fixes #17 
r? @jonhoo

Add support for C++ symbol demangling

---

src/lib.rs

Following discussion in #30, it seems clear that asserting that all of a compilation unit's child units are contained within it is wrong. It happens in the real world, and is thus not *impossible*.

Remove invalid debug assertion

---

src/bin/addr2line.rs
src/lib.rs
tests/integration_test.rs

Fixes #29 
Now caches every line number row, instead of using a skiplist.
`locate` API has changed to require `&mut self` (and no longer uses `RwLock` internally). Not sure if this is a problem, but I wanted to get it working correctly before adding complications like that.
Performance is better for both CPU and memory when testing symbolication of 26000 addresses in a 53MB library. Timing from `/usr/bin/time -f '%e\t%M'`:
```
Without functions:
Before: 0.29	32396
After:  0.18	32260
With functions:
Before: 1.89	72580
After:  1.73	72320
```

Handle out of order sequences

---

src/bin/addr2line.rs
src/lib.rs

Furthermore, ignore address ranges completely, because they are unreliable.
I have a shared library that was compiled with clang version 3.7.1
which has invalid address ranges such as:
[14] range entry    0x00000001 0x00000001
The line table contains rows for the addresses that should have been here,
so we now ignore the address range in .debug_info and use only the line table
instead.
Fixes #42

Handle units without address ranges in .debug_info

---

Cargo.toml
README.md

Breaking bump because `Mapping::locate` changed from `&self` to `&mut self`.
r? @philipc

Bump to version 0.5.0

---

src/bin/addr2line.rs
src/lib.rs
tests/integration_test.rs

The integration test was failing because we are returning a filename for the main() wrapper, but binutils doesn't. I changed the integration test to ignore this case.
Also run rustfmt and clippy.

Various cleanup

---

Cargo.toml
benches/bench.rs
tests/integration_test.rs

The fixture was built from the current source of this crate with:
```
RUSTFLAGS=-g cargo build --release
objcopy --only-keep-debug target/release/addr2line fixtures/addr2line-release
```

Add benchmark

---

tests/integration_test.rs

Experiencing frequent hangs when running them under code coverage tools.
I've also seen a hang running standalone too.
When the hang occurs, CPU usage drops to 0 and strace says the test
process is waiting on a futex.

Ignore self tests for now

---

Cargo.toml
src/bin/addr2line.rs
src/lib.rs
tests/integration_test.rs

Fixes #3 
This gives results that match binutil addr2line for all addresses except for a couple of oddities (eg zero size symbol).

Add option to use symbol table

---

src/lib.rs
tests/correctness.rs

And ignore sequences and functions that start at 0.
Fixes #67

 Handle overlapping unit ranges 

---

Cargo.toml
examples/addr2line.rs
src/lib.rs

It would have been nice to change `FunctionName` to hold `Cow<str>` instead of `gimli::Reader` so that symbols could be `FunctionName`s too, but the lifetime on `Reader::to_string_lossy` doesn't allow that.
Demangling is a bunch of small functions again, but I don't see how to do better.

 Add symbol table fallback to addr2line example 

---

src/lib.rs

#70 was an incomplete fix for overlapping ranges; it only handled overlapping unit ranges, and not overlapping function ranges.
No changes to the external API yet, but `FullContext` could easily be removed after this.
Also a couple of refactoring commits that aren't really related.

Use one IntervalTree per unit

---

Cargo.toml
src/lib.rs

Lazycell has `#![no_std]` support. We give up sync-ness, but that's not needed for std inclusion.

Switch to lazycell

---

Cargo.toml
src/lib.rs

Also use the `Object` trait instead of `File` (see https://github.com/gimli-rs/object/issues/53).
~~This requires https://github.com/gimli-rs/gimli/pull/305.~~
I played a bit with using `Rc/Arc<Cow<'input, [u8]>>` instead of `EndianRcSlice`, but wasn't sure it was worth the API complexity. So I think `Context::new` should be the simple high level interface, and consumers with more specific needs can use `Context::from_sections`.
Before:
```
test context_new_and_query_location       ... bench:     951,031 ns/iter (+/- 79,277)
test context_new_and_query_with_functions ... bench:   1,760,225 ns/iter (+/- 54,934)
test context_new_location                 ... bench:     760,223 ns/iter (+/- 57,231)
test context_new_with_functions           ... bench:     751,183 ns/iter (+/- 55,055)
test …
```

Update object to 0.9.0

---

.travis.yml
Cargo.toml
ci/script.sh
src/lib.rs

Fixes #90 
I also changed the travis builds so there's not quite so many builds.
This still needs a gimli update, so the nightly travis build will fail.

Implement no_std support

---

src/lib.rs

Fixes some of https://github.com/rust-lang/backtrace-rs/issues/232#issuecomment-517578935.

Improve performance for line number program handling

---

src/lib.rs

Fixes #132. r? @philipc 
I don't know if I'm using the right words in the commit message, how to find out what the type of the "broken" units is or what this means about the validity of the DWARF data. I also don't know how to slim the testcase down into something that could become a real test.

Ignore broken units in Context<R>::from_sections.

---

src/lib.rs

When one already has a `gimli::Dwarf` object created with a custom `gimli::Dwarf::load` invocation, it's not very convenient to deconstruct it to separate sections just to create a `Context`.
Given that `Context` already uses `gimli::Dwarf` internally, let's expose an additional constructor that allows to take it.

Add `Context::from_dwarf` constructor

---

benches/bench.rs

Fix address retrieval in `cargo bench`
First 200 lines from nm can contain irrelevant symbols which are all filtered out and benchmark starts testing no-op.
Change code to make sure that we always have at least 200 symbols *after* filtering out.
(I'm not sure if this was broken forever, or just depends on the distro / nm version.)
Before:
```
test context_new_and_query_location       ... bench:   3,483,195 ns/iter (+/- 176,722)
test context_new_and_query_with_functions ... bench:   3,500,515 ns/iter (+/- 171,316)
test context_new_location                 ... bench:   3,548,175 ns/iter (+/- 428,981)
test context_new_with_functions           ... bench:   3,935,070 ns/iter (+/- 1,562,079)
test context_query_location               ... bench:           0 ns/iter (+/- 0)
test …
```

Fix address retrieval in `cargo bench`

---

benches/bench.rs

Remove redundant benchmark

---

Cargo.toml
benches/bench.rs
src/lib.rs

Also disable parallel codegen for benchmarks. This improves the benchmarks due to better inlining, and makes them a more reliable tool for determining the effect of code changes.
Before:
```
test context_new_and_query_location       ... bench:   3,111,057 ns/iter (+/- 530,666)
test context_new_and_query_with_functions ... bench:   4,172,368 ns/iter (+/- 556,175)
test context_new_location                 ... bench:   2,857,732 ns/iter (+/- 152,999)
test context_query_location               ... bench:     713,752 ns/iter (+/- 45,922)
test context_query_with_functions         ... bench:   4,526,699 ns/iter (+/- 567,636)
```
After:
```
test context_new_and_query_location       ... bench:   2,953,517 ns/iter (+/- 103,705)
test context_new_and_query_with_functions ... bench:   3,803,000 ns/iter …
```

Add benchmarks for the lazily parsed data

---

Cargo.toml
src/lib.rs

```
name                                        before ns/iter  after ns/iter  diff ns/iter   diff %  speedup
context_new_and_query_location_rc           2,801,330       2,756,426           -44,904   -1.60%   x 1.02
context_new_and_query_location_slice        799,066         813,226              14,160    1.77%   x 0.98
context_new_and_query_with_functions_rc     3,669,702       3,353,516          -316,186   -8.62%   x 1.09
context_new_and_query_with_functions_slice  1,185,584       1,235,567            49,983    4.22%   x 0.96
context_new_parse_functions_rc              57,176,047      39,507,103      -17,668,944  -30.90%   x 1.45
context_new_parse_functions_slice           26,040,739      28,291,537        2,250,798    8.64%   x 0.92
context_new_parse_lines_rc …
```

Use gimli::EntriesRaw

---

src/lib.rs

```
name                                        before ns/iter  after ns/iter  diff ns/iter   diff %  speedup
context_new_and_query_location_rc           2,490,696       2,447,360            -43,336   -1.74%   x 1.02
context_new_and_query_location_slice        772,800         773,439                  639    0.08%   x 1.00
context_new_and_query_with_functions_rc     3,068,885       3,021,044            -47,841   -1.56%   x 1.02
context_new_and_query_with_functions_slice  1,180,680       1,144,850            -35,830   -3.03%   x 1.03
context_new_parse_functions_rc              37,416,109      30,829,671        -6,586,438  -17.60%   x 1.21
context_new_parse_functions_slice           26,969,411      24,411,324        -2,558,087   -9.49%   x 1.10
context_new_parse_lines_rc …
```

Avoid moving result of read_attribute

---

Cargo.toml
src/lib.rs
tests/parse.rs

`IntervalTree` doesn't perform as well as a simple tree of `Vec`s. Note that a `Vec` tree can't handle partially overlapping intervals, but we don't need that.
```
name                                        before ns/iter  after ns/iter  diff ns/iter   diff %  speedup
context_new_and_query_location_rc           2,427,320       2,432,182             4,862    0.20%   x 1.00
context_new_and_query_location_slice        765,873         758,006              -7,867   -1.03%   x 1.01
context_new_and_query_with_functions_rc     2,993,102       2,959,278           -33,824   -1.13%   x 1.01
context_new_and_query_with_functions_slice  1,133,112       1,152,324            19,212    1.70%   x 0.98
context_new_parse_functions_rc              31,235,025      33,387,535        2,152,510    6.89%   x 0.94 …
```

Replace IntervalTree with Vec

---

benches/bench.rs
src/lib.rs

I'm not sure about this change, and I'm inclined to not merge it for now. While it does show benefits for the backtrace-rs benchmarks, it doesn't for the addr2line benchmarks, and it significantly slows down the parsing and increases the memory usage.
```
addr2line benchmarks:
name                                        before ns/iter  after ns/iter  diff ns/iter   diff %  speedup 
context_new_and_query_location_rc           2,432,182       2,512,901            80,719    3.32%   x 0.97 
context_new_and_query_location_slice        758,006         759,694               1,688    0.22%   x 1.00 
context_new_and_query_with_functions_rc     2,959,278       3,156,481           197,203    6.66%   x 0.94 
context_new_and_query_with_functions_slice  1,152,324       1,254,633           102,309 …
```

Cache function attributes

---

.travis.yml
Cargo.toml
ci/script.sh
src/lib.rs
tests/parse.rs

addr2line can't do anything useful without allocating, and the alloc crate
is now stable, so having a separate alloc feature is not required.
Instead, you should simply disable all features.
Also fix `cargo test` with features disabled.
Note that the `object` feature currently requires std. This will be
relaxed in future once the following are addressed:
- the `object` crate needs updating for its `alloc` feature to work on stable
- the `stable_deref_trait` crate needs a new release for its `alloc`
feature to work on stable

Delete alloc feature

---

examples/addr2line.rs

Somewhere between version 2.22 and 2.30, the binutils addr2line output for unknown lines changed from "??:0" to "??:?".
@kentfredric Can you check this fixes the tests for you?

addr2line: update to match newer binutils

---

Cargo.toml
benches/bench.rs
src/lib.rs
tests/parse.rs

This makes it possible get access to the internal parsed `Dwarf` and `Unit`. It also allows access to the `UnitOffset` corresponding to the DIE of a frame. This is very useful for https://github.com/bjorn3/pretty_backtrace/tree/var_guard.

Allow access to the parsed dwarf 

---

Cargo.toml
ci/script.sh
src/lazy.rs
src/lib.rs

This commit trims the dependencies of `addr2line` to be used in the
`backtrace` crate. The purpose here is to slowly trim down the list of
dependencies to make it easier to eventually include this in the
standard library. Fow now this handles three previously required
dependenies of `addr2line`:
* `smallvec` - this is made optional where if not present a standard
`alloc::vec::Vec<T>` is used.
* `fallible-iterator` - this is simply made optional.
* `lazycell` - this is dropped in favor of a small hand-rolled
implementation.
The new features are enabled by default and the thinking is that the
`backtrace` crate would disable all these features by default. If the
`std` feature of `backtrace` is activated it'd activate these features,
however.

Trim dependencies of `addr2line` for `backtrace`

---

Cargo.toml
ci/script.sh
src/lib.rs
tests/aux/Cargo.toml
tests/aux/src/lib.rs
tests/correctness.rs
tests/output_equivalence.rs

This commit is an attempt to fix rust-lang/backtrace-rs#327. The
behavior seen there was that CGUs would often overlap each other which
would cause a previous loop which tried to ensure CGUs didn't overlap to
avoid some CGUs being candidates for symbolizing.
To fix the issue this commit removes the loop which alters the range of
each CGU. Instead CGUs are only sorted by their starting function
address. When looking up a CGU for a function the CGU's address range is
used to initially filter the sort but afterwards the units function
address table is also consulted. The first CGU which contains the
function address is what ends up getting returned.

Don't truncate ranges of units

---

ci/script.sh
tests/output_equivalence.rs

The test executable path differs between `cargo test` and `cargo tarpaulin`.

Fix code coverage in CI

---

src/lib.rs

Fixes #167 
I think this is worth a patch release too.

Don't assert for functions with overlapping address ranges

---

benches/bench.rs
src/lib.rs

This is a significant rebase of the great work done by @mstange in #176 . Closes #176 .
The description from that PR still applies:
>    - There are now two levels of function parsing laziness.
>        - The first level creates only the function ranges for "outer functions" (DW_TAG_subprogram) and writes down each outer function's dw_die_offset. By necessity, when parsing the list, we need to iterate over all abbrevs and attributes of the unit, including the ones for any nested tags for inlined functions, but we try to keep the work we do for them to a minimum.
>        - The second level is done once we look up an address that falls into an outer function's address range. At that point, we parse the entries for that outer function again, starting at the recorded dw_die_offset. We parse …

Improve performance by parsing function contents lazily

---

src/lib.rs
tests/correctness.rs

Also fix `FrameIter` to handle a missing location (just something I noticed when testing each of the skips individually).
Fixes #174 (cc @mstange)

Don't skip entries with a zero address

---

Cargo.toml

This applies the same change as gimli-rs/gimli#503 to this crate.
(also see https://github.com/rust-lang/backtrace-rs/issues/328 for some context)

Prepare for inclusion into libstd

---

src/lib.rs

DWARF version <= 4 may not have index 0. As a workaround, we add a dummy
value, which should be fine since presumably 0 index should not be
referenced in any valid DWARF file <= v4. Fixes gimli-rs/addr2line#190.

Handle older DWARF versions better

---

src/lib.rs

We were converting the reference to a unit offset, but incorrectly continuing to use the old unit. This resulted in errors such as `OffsetOutOfBounds` or `NoEntryAtGivenOffset`.
Fixes #192 (cc @SWW13)

Fix handling of `DW_FORM_ref_addr` in `name_attr`

---

src/lib.rs

I have a use-case where I want to get the source locations for a range of addresses. The simple approach is to just call `Context::find_location` on each address in the range - this works, but it is extremely slow since:
1. it repeats all the setup cost for each byte
2. the caller has no idea how much space each Location spans, so ends up redundantly probing the same locations over and over
This PR implements `find_location_range` which returns an iterator of all the locations in the range. It is much more efficient because it amortizes all the setup cost and directly returns the locations in the range. In addition to the Location, it also returns the address and length of the byte range the location describes.
It also implements `find_location` in terms of returning a single Location …

Add find_location_range

---

src/lib.rs

Fixes #198 - `find_units_range` can repeatedly return different subranges of the same unit, so make sure the iteration is constrained to that range. Otherwise it re-iterates the entire range repeatedly.
Minimal perf effect, mostly an improvement:
```
name                                        base ns/iter  pr ns/iter  diff ns/iter   diff %  speedup
context_new_and_query_location_rc           2,395,624     2,320,514        -75,110   -3.14%   x 1.03
context_new_and_query_location_slice        860,152       889,665           29,513    3.43%   x 0.97
context_new_and_query_with_functions_rc     2,692,048     2,751,044         58,996    2.19%   x 0.98
context_new_and_query_with_functions_slice  1,135,428     1,128,007         -7,421   -0.65%   x 1.01
context_new_parse_functions_rc …
```

Fix issue https://github.com/gimli-rs/addr2line/issues/198

---

.github/workflows/rust.yml
Cargo.toml
examples/addr2line.rs
src/lib.rs

Primarily this involves handling `DW_AT_abstract_origin` and `DW_AT_specification` that point to the supplementary debug info.
Also fixes #206

Handle supplementary object files

---

src/lib.rs

Fixes #43 
I don't know if this is the best way to do it, but it seems to work.
Normally I would use the std for this, but apparently this is a no_std crate. I guess for binary size?

Added windows paths support

---

examples/addr2line.rs

Forcefully flush stdout after each address is handled. This allows to use
addr2line in a "coprocess" mode, in which another process forks/execs
addr2line, establishes two uni-directional pipes for passing input addresses
and reading back responses, and uses addr2line in a client/server fashion.
This is done for amortizing start up costs and make stack symbolization as
cheap as possible.
The problem with the above "coprocess" mode is that because addr2line is
getting Unix pipes for stdin/stdout, std::io::stdin()/std::io::stdout() will
switch to fully buffered mode, instead of line-buffered one that happens when
stdin/stdout is wired to interactive shell. Because of that buffering, driving
application will never get response (unless it's bigger than internal buffer,
which is quite big, …

examples/addr2line: flush stdout after each response

---

README.md

#106 is hit if object and addr2line are added to Cargo.toml where object version does not match the version addr2line depends on. addr2line re-exports the correct version, which is now referred to instead.
Unfortunately, there doesn't seem to be a way to automagically link to the correct doc version for object in the quickstart.

quickstart: refer to re-exported object crate instead

---

Cargo.toml
examples/addr2line.rs
src/lib.rs

Avoid copying the debug into RAM & instead use borrows to utilize the 0-copy facility of gimli.
Resolves #212

Switch addr2line to use EndianReader.

---

src/lib.rs

Some compilers only emit the full ranges in .debug_aranges,
leaving only low/high attributes on the CU, which may overlap
with other CUs.  We already have workarounds for this, but it's
better to use the ranges if we have them.

Use .debug_aranges

---

CHANGELOG.md
Cargo.toml
src/lib.rs

This can occur for unpacked debuginfo.

Don't ignore aranges with address 0

---

src/lib.rs

Allow `Context` to be `Send`

---

Cargo.toml
examples/addr2line.rs

This updates the `addr2line` example to `clap` v3.1.6. `clap` does have an MSRV of 1.54.0 on any v3 version, but this is unlikely to matter much in this case since it is just used as a dev dependency
The changes were pretty straightforward (and made the example more succinct), and everything seems to match the old behavior
_Just a basic test_
```
Running `target/debug/examples/addr2line -e /tmp/a.out -f 0x1139`
main
/tmp/test.c:3
```
_Old `--help`_
```
hardliner 0.1
A fast addr2line clone
USAGE:
addr2line [FLAGS] [OPTIONS] --exe <filename> [addrs]...
FLAGS:
-a, --addresses       Display the address before the function name, file and line number information.
-s, --basenames       Display only the base of each file name.
-C, --demangle        Demangle function names. Specifying a specific …
```

Update clap to v3.1

---

.github/workflows/rust.yml
tests/output_equivalence.rs

rust 1.60 has started inlining more functions, so the test was reaching
addresses in the backtrace that we handle differently from
binutils addr2line. However, our handling is probably more correct
(and matches llvm), so we don't want to change to match binutils.
Fix by preventing inlining of another function.

Fix output_equivalence test

---

examples/addr2line.rs

The _perf_ utility uses either _libbfd_ or _addr2line_ to obtain information about inlined symbols (the record-time unwinding itself is handled by _libunwind_). Both option uses _libbfd_ under the hood, and it seems that _libbfd_ lacks the functionality of properly constructing a binary search index before doing the mass lookups. As a result, it runs like hot garbage for a lot of debug binaries.
The option to use an out-of-process _addr2line_ was originally added for Debian linking license reasons, but it turns out that with a little tweaking we can drop in a different addr2line implementation as well. With these modifications and Gimli's addr2line dropped into /usr/local/bin, `perf report` runs magnitudes faster (~100x? didn't measure) and there doesn't appear to be major issues. …

cli: Fixes and refactoring for perf support

---

examples/addr2line.rs
src/lib.rs

Fixes #248.
In addition to the missing unit ranges, there was a bug where we weren't able to find the file name that was added during line rows iteration, and we were creating an absolute path instead of a relative path.

Improve compatibility with .so files produced by perf inject --jit

---

src/lazy.rs

In this function you use the unsafe keyword for almost the entrie function body. However, I found that only 1 operation are real unsafe operation (see the list below). 
We need to mark unsafe operations more precisely using unsafe keyword. Keeping unsafe blocks small can bring many benefits. For example, when mistakes happen, we can locate any errors related to memory safety  within an unsafe block. This is the balance between Safe and Unsafe Rust. The separation is designed to make using Safe Rust as ergonomic as possible, but requires extra effort and care when writing Unsafe Rust. 
**Real unsafe operation list:**
1. dereferencing raw pointers (*ptr)
Hope this PR can help you.
Best regards.
**References**
https://doc.rust-lang.org/nomicon/safe-unsafe-meaning.html …

The scope of the unsafe block can be appropriately reduced

---

Cargo.toml

In particular, picking up https://github.com/gimli-rs/object/pull/443.

Bump object to 0.29

---

.github/workflows/rust.yml
Cargo.toml

Due to changes in stability of the split-debuginfo options, we need to only set split-debuginfo=packed for macOS.
There's no target-specific cargo config setting for split-debuginfo, so we conditionally set environment variables.
Closes #256

Only set split-debuginfo=packed for macOS

---

.github/workflows/rust.yml
Cargo.toml
benches/bench.rs
examples/addr2line.rs
src/builtin_split_dwarf_loader.rs
src/function.rs
src/lazy.rs
src/lib.rs
tests/correctness.rs

This is pretty invasive. It also depends on gimli-rs/gimli#637
To make split DWARF work, we'll ultimately need to be able to create the correct `gimli::Dwarf` and `gimli::Unit`s. The former is a blend of sections from the main (at a minimum, .debug_addr) and dwo files. The latter is parsed from the dwo and then has `copy_relocated_attributes` called with the skeleton unit from the main file.
We also don't want to force the loading of all split DWARF data up front for performance reasons.
This means we need a mechanism for lazy loading of split DWARF data (enter the new `SplitDwarfLoader` trait) that can be provided by the addr2line consumer. Once the consumer loads the correct `gimli::Dwarf` and returns it to addr2line, we can produce the correct `gimli::Unit`.
We then have to pass the …

Support split DWARF

---

src/function.rs
src/lib.rs

There is a spec issue [1] with how DW_AT_call_file is specified in DWARF 5. Before, a file index of 0 would indicate no source file, however in DWARF 5 this could be a valid index into the file table.
Implementations such as LLVM generates a file index of 0 when DWARF 5 is used.
Thus, if we see a version of 5 or later, treat a file index of 0 as such.
[1]: http://wiki.dwarfstd.org/index.php?title=DWARF5_Line_Table_File_Numbers
Thanks to https://github.com/gimli-rs/gimli/pull/606 for the reference of the spec issue.

Fix handling of DW_AT_decl_file = 0.

---

examples/addr2line.rs
src/builtin_split_dwarf_loader.rs
src/lib.rs
tests/correctness.rs

I was unable to generate DWARF with mingw that had non-UTF8 paths. Somewhere in the toolchain the path is being lossily converted to UTF8. We may find a situation in which the DWARF doesn't contain UTF8 in the future, but until then we try to do a lossless conversion to UTF8, and return an error if that fails.

Enable builtin_split_dwarf_loader for Windows

---

src/lib.rs

We never resize the unit ranges, units, or sup units that we parsed -- they stay what they were when we instantiated the Context object. As such, we don't need to store `Vec` objects, which include a capacity. Do what we do for the `Functions` type and just store boxed slices. Doing so cuts a machine word of each, but also trims heap allocations to the minimal size required in the process.

Store boxed slices instead of `Vec` objects in `Context`

---

src/lib.rs

The column is always valid if a line was specified.
Closes #179

Fix handling of column 0 in the line info

---

src/function.rs
src/lib.rs
src/line.rs
src/unit.rs

Prompted by the clippy warnings.
`dwarf_and_unit_dwo` changes are simpler if whitespace is ignored.

Lazy parsing cleanups

---

src/line.rs

We were failing to return location ranges when the following conditions held:
- the unit ranges differed from the sequence ranges
- there is a gap in the sequence ranges, and the probe range begins in that gap
This is unlikely to occur in practice. I reproduced the error by modifying addr2line to give every unit a single range of (0, !0).

Fix find_location_range

---

src/line.rs
src/unit.rs

```
context_query_location                1,150,942       984,457            -166,485  -14.47%   x 1.17
context_query_with_functions          2,463,730       2,276,523          -187,207   -7.60%   x 1.08
```

Don't use the location range iterator for `find_location`

---

src/unit.rs

This is now closer to ascending order (the exception being when there are overlapping ranges).

Reverse the order of ranges returned by find_location_ranges

---

src/bin/addr2line.rs
src/lib.rs
src/loader.rs

This displays line number information for all known addresses.
#306 will improve the ordering for the output of this.

Add --all option to addr2line binary

---

src/unit.rs

These don't normally have ranges anyway, but it is possible for them to have a DW_AT_stmt_list that points to the same program that contains ranges for a compilation unit, and loading the ranges from that is wrong.
This used to work because our search would find the compilation unit first, but we changed the search order and now it was finding the partial unit.
Closes #311

Don't parse ranges for partial units

---

src/loader.rs

This speeds up the initial parsing of units when there are many small units that share abbreviations.
This was encountered for postgresql in opensuse/tumbleweed.

Enable abbreviations cache for duplicates

---

src/lib.rs

The context was already using `Arc` internally, so this allows the caller to use the same `Dwarf` for other purposes.

Add Context::from_arc_dwarf

---

.github/workflows/rust.yml
.gitmodules
Cargo.toml
src/lib.rs
testoutput/dwarf/tombstone-loc-0
testoutput/dwarf/tombstone-loc-1
testoutput/dwarf/tombstone-loc-addend
testoutput/dwarf/tombstone-loc-max
testoutput/dwarf/tombstone-loclists-0
testoutput/dwarf/tombstone-loclists-addend
testoutput/dwarf/tombstone-loclists-max
tests/testinput.rs

This covers some but not all cases of tombstones.
In particular, we don't have a test for a DW_LNE_set_address tombstone in the middle of a line number sequence.
This also handles an integer overflow for a tombstone address in DW_AT_low_pc. We already did the right thing in release builds.

Add tests for tombstones

---

CHANGELOG.md
Cargo.lock
Cargo.toml

This includes a `gimli` update, which includes a fix for handling of DWARF tombstones. Partial fix for #326

Release 0.24.2

---

Cargo.toml

These now require the testinput submodule.

Don't include tests in package

---

src/lib.rs
src/loader.rs

Hi,
I'm writing some analysis tool that uses addr2line - thanks a lot for it!
It turns out that I also need to find the symbol containing an address. `Loader.find_symbol()` gives me the name, but I also need the symbol address.
Will it be possible to add a method that also returns the address? One alternative is to return `Option<(&str, u64)>`, as what is currently in this branch, and another alternative is to return `Option<&SymbolMapName>`, both are fine with me.
Thanks!
Noam

Add find_symbol_and_addr, which also returns the symbol base address

---

src/bin/addr2line.rs
src/loader.rs

I suggested to my coworker to use the Rust addr2line instead of the binutils, since it took a long time using the binutils version. However, he was using the `-j/--section` option of binutils addr2line, which wasn't implemented. So I implemented it. It just requires adding the section address before doing the lookup.
What do you think?

Add -j/--section option, to read offsets relative to section

---

src/line.rs

On Windows Clang can produce DWARF debug information containing paths to **DW_AT_name** and **DW_AT_comp_dir** with unix-stlye slashes. for example **C:/myproject/main.cpp**. In that case case addr2line mistakenly concatenating absolute path to file with compilation directory

fix: detecting windows root paths with unix-style separators

---

Cargo.lock
Cargo.toml

Since [1], this will come automatically from `rustc-std-workspace-core` and the crates.io dependency should no longer be specified.
[1]: https://github.com/rust-lang/rust/pull/141993

Remove `compiler-builtins` from `rustc-dep-of-std` dependencies

---

src/function.rs
src/line.rs
src/unit.rs

Unstable sorting has significantly better code size (and often better performance too). With this change (rebased on top of v0.25.0, which is what std currently uses) the .text size of Rust hello world (with `-Clto=fat -Copt-level=s`) goes from 297120 to 290351 (-2.23%).
I do not know *that* much about addr2line, so I cannot guarantee that this code is fine with unstable sorting. But I think it should be fine since it always sorts on addresses, which are either unique or nondeterministic anyways (as mentioned in one comment even). So it should not make a significant difference.

Use unstable instead of stable sorts

---

src/line.rs

This doesn't matter for `Lines::find_location`, but it does matter for `Lines::find_location_range`, because we might sort the sequences so that the empty sequence comes later, and start the iteration at the empty sequence.
Noticed in #358

Ignore empty line sequences
