- src/lib.rs
- tests/integration_test.rs
This PR fixes all [clippy](https://github.com/Manishearth/rust-clippy) warnings.
I will re-base onto master once #7 is merged.
> Fix all clippy warnings

- README.md
Includes more information about the library, how to quickly add it to your project, and a detailed usage example for both the library and the binary.
> Write up a better README

- src/lib.rs
Fixes code to work with changes introduced in gimli-rs/gimli#165.
> Handle gimli exposing errors from attr()

- src/lib.rs
This PR implements one of the optimizations discussed in #2. In particular, it lazily instantiates a list of `gimli::StateMachine` every `n` (currently 100) `LineNumberRow` as it walks the line rows for a `Unit`. For each cached row, it also tracks the address the state machine encountered at that point, allowing us to binary search over this "skiplist" when we're given a new address, rather than always doing a linear scan from the start of the unit. The speed-up is quite significant: ~100x for file/line lookups, and ~10x for file/line/function lookups.
```console
$ objdump --dwarf=info target/release/vote | grep -E 'subprogram|subroutine' | wc -l
92572
$ objdump -C -x --disassemble -l target/release/vote | grep -P '0[048]:' | awk '{print $1}' | sed 's/:$//' > addresses.txt
$ wc -l …
```
> Implement lazy binary search for line rows

- src/lib.rs
Now that gimli-rs/gimli#168 has landed, we can implement the heuristic proposed by @fitzgen in https://github.com/gimli-rs/addr2line/pull/14#issuecomment-266125440 to dynamically determine the interval used by the binary search skiplist introduced in #14 (which uses a hardcoded interval of 100 rows). In particular, this PR approximates `sqrt(#rows)` as suggested by @fitzgen in https://github.com/gimli-rs/addr2line/issues/2#issuecomment-265636994.
This PR also disables the skiplist for units with very few (estimated) rows, which causes some memory savings, at the cost of a minor runtime increase. We can discuss whether we want this behavior, and if we do, what the threshold is.
Performance comparison (`master` is without binary search, `static` is #14, `dynamic` is this PR):
> Dynamic skiplist interval

- src/lib.rs
Now that https://github.com/Kimundi/owning-ref-rs/issues/19 has been resolved with `ObjectHandle` gaining a `try_new` method, we can get rid of the nasty `.expect()` in `Mapping::new_inner`, which would panic if the debug symbols for a given binary were invalid. Now, the error is instead exposed directly to the caller through the returned `Result`.
> Expose symbolication errors at creation time

- Cargo.toml
> Add crates.io badges and categories

- src/lib.rs
When parsing range lists, we must use the base address of the
compilation unit, rather than that of the entry referring to the
range list.
Also try parse to DW_AT_entry_pc if DW_AT_low_pc is not present.
This is for compatibility with GNU tools.
Fixes #30
> Use base address of compilation unit for range lists

- src/lib.rs
- tests/integration_test.rs
Also some noise from running newer rustfmt.
Fixes #35
> Handle DW_AT_MIPS_linkage_name and DW_AT_specification

- src/lib.rs
> Ignore subroutines with no name

- Cargo.toml
- src/lib.rs
Fixes #37 
I'm open to bikeshedding for the name `BufferMapping`.
cc @m4b
> Add BufferMapping

- src/lib.rs
> End sequence

- benches/bench.rs
- tests/integration_test.rs
We were trying to write all addresses to the oracle before reading
anything back.
Fixes #57
> Fix write deadlock

- src/lib.rs
See commits for details.
The second commit has a regression for the `build_default` benchmark. This appears to be due to the longer lifetimes of abbreviations. perf shows more time spent in jemalloc. It may be possible to avoid this if we had something like https://github.com/gimli-rs/gimli/issues/251.
> Performance improvements

- src/lib.rs
> Don't fail if a debug section is missing

- examples/addr2line.rs
- src/lib.rs
Also some addr2line output changes to make it easier to compare against other tools.
> Handle more name attributes

- Cargo.toml
- benches/bench.rs
- examples/addr2line.rs
- tests/correctness.rs
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
> deps: update memmap to 0.6

- Cargo.toml
- src/lib.rs
- tests/correctness.rs
I think this is good enough to finally do a release? If so, I can tag and publish.
> Update dependencies and minor fixes

- Cargo.toml
- ci/script.sh
- examples/addr2line.rs
- src/lib.rs
This will allow implementation of no_std support in the future.
> Remove Path usage

- Cargo.toml
> Bump to 0.7.0

- CHANGELOG.md
- Cargo.toml
> Update changelog and bump version to 0.9.0

- benches/bench.rs
This should be both faster and more reliable across different distros.
> Use object crate for bench addresses

- benches/bench.rs
```
test context_new_and_query_location_rc          ... bench:   2,924,965 ns/iter (+/- 141,887)
test context_new_and_query_location_slice       ... bench:   1,195,508 ns/iter (+/- 45,849)
test context_new_and_query_with_functions_rc    ... bench:   3,718,841 ns/iter (+/- 217,461)
test context_new_and_query_with_functions_slice ... bench:   1,546,655 ns/iter (+/- 106,857)
test context_new_parse_functions_rc             ... bench:  59,817,116 ns/iter (+/- 689,141)
test context_new_parse_functions_slice          ... bench:  23,258,062 ns/iter (+/- 514,862)
test context_new_parse_lines_rc                 ... bench:  12,011,106 ns/iter (+/- 417,340)
test context_new_parse_lines_slice              ... bench:   7,884,877 ns/iter (+/- 268,838)
test context_new_rc                             ... …
```
> Add EndianSlice benchmarks

- Cargo.toml
> chore: Upgrade object to 0.16, smallvec to 1.0

- src/lib.rs
> Avoid linear search for DW_FORM_ref_addr

- Cargo.toml
> Update object to 0.20

- CHANGELOG.md
- Cargo.toml
- benches/bench.rs
- examples/addr2line.rs
- src/lib.rs
> Release 0.14.0

- CHANGELOG.md
- Cargo.toml
> Bump version to 0.14.1

- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.toml
> Release 0.16.0

- README.md
Fixes https://github.com/gimli-rs/addr2line/issues/230
> Fix link to File::parse

- src/lib.rs
> Dedupe comp-dir/directory in line-table paths

- src/function.rs
- src/lib.rs
Closes https://github.com/gimli-rs/gimli/issues/621
@vlovich Can you test that this covers everything you need?
> Handle DW_FORM_addrx

- CHANGELOG.md
- Cargo.toml
- benches/bench.rs
- examples/addr2line.rs
- tests/correctness.rs
- tests/parse.rs
> Release 0.18.0

- src/function.rs
- src/lib.rs
gimli::Dwarf already has a reference to the supplementary sections.
cc @khuey
> Remove RawDwarf

- benches/bench.rs
- examples/addr2line.rs
- src/builtin_split_dwarf_loader.rs
- src/function.rs
- src/lib.rs
- tests/correctness.rs
See individual commits.
cc @khuey
> Refactor split DWARF support

- examples/addr2line.rs
> Improvements for examples/addr2line

- Cargo.toml
- benches/bench.rs
- examples/addr2line.rs
- src/builtin_split_dwarf_loader.rs
- src/function.rs
- src/lib.rs
- tests/correctness.rs
- tests/output_equivalence.rs
- tests/parse.rs
The crate isn't compatible with any 2015-only compiler, so it can use a more recent Rust edition.
> Update to Edition 2018

- CHANGELOG.md
This pull request fixes a small typo.
> FIx a typo

- src/lib.rs
Also remove unneeded extern crate declarations.
> Add the gimli export back in

- .github/workflows/rust.yml
- Cargo.toml
- examples/addr2line.rs
Also update libtest-mimic which depends on clap too.
> Update clap to 4.3.21

- .github/workflows/rust.yml
- src/loader.rs
N_OSO symbols in the executable file contain the path to the object files.
> Add support for Mach-O unpacked debuginfo

- Cargo.toml
- src/function.rs
- src/lib.rs
- src/line.rs
- src/unit.rs
Reduces the number of parameters.
Closes #294
> Use gimli::UnitRef

- src/unit.rs
In rare situations we were unnecessarily checking an extra unit.
> Improve binary search of unit ranges

- scripts/benchmark-addr2line-docker.sh
- Set context directory to scripts/docker.
- Reuse host's CARGO_HOME.
- Remove container afterwards.
- Use --interactive when possible to allow ctrl-c.
> Docker tweaks
